### ISSUE TITLE
srcMLException

### ISSUE THREAD

**Issue by yingdehuijin** [srcML/pylibsrcml#4]
Hi,
i use srcml to handle the code in my dataset.I want to generate the xml file from the .java file.I use the method srcml.srcml(inputfile,outputfile).To each java method , i have no choice but to generate the xml file.When handle the large size methods,i found srcml can only transform java files to xml files 1200 times,then it will report errors "pylibsrcml.exception.srcMLException: Recieved invalid return status: 5" .
How can i address the problem or can you give me some advise about how to transform java files of large size to xml files?
Thank you for your reply!

**Comment by mjdecker** [comment]
There was a file descriptor leak in libsrcml.  This has been fixed and will be in the next release (~ a month).

**Comment by yingdehuijin** [comment]
> There was a file descriptor leak in libsrcml. This has been fixed and will be in the next release (~ a month).

thank you,i have solved the problem
